# Generated by Django 4.1.4 on 2022-12-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channel_name',
            field=models.CharField(default='m4Okt7ubfNHrp76s', max_length=16),
        ),
    ]
